### PR TITLE
Add Full screen button and fix redux undefined tab

### PR DESCRIPTION
**Pull request by laviro**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Screenshots:
main screen:
image

full screen:
image

**Comment by laviro** [comment]
Yeah, from what I see the 2 terminal modals are overlapping each other..
I will put the modal in a separate file and connect it to redux so there will be only one modal
which will get updated by the current active tab logs.

**Comment by laviro** [comment]
Fixed that @ShimShtein

**Comment by ShimShtein** [comment]
Merged, thanks @laviro!

**Pull request merged**
