### PR TITLE
Disable terminal auto-scroll when user have scrolled up

### PR DESCRIPTION
**Pull request by laviro**

### CODE REVIEW

**Comment by laviro** [comment]
thanks @ShimShtein I will take a look

**Comment by ShimShtein** [comment]
This one needs a rebase

**Comment by laviro** [comment]
Blocked by #80

**Comment by ShimShtein** [comment]
@laviro, this needs a rebase too.

**Comment by laviro** [comment]
updated, thanks @ShimShtein

**Comment by laviro** [comment]
@ShimShtein could you take a look?
I found the reason the scrolling didn't work smoothly and fix it.

**Comment by ShimShtein** [comment]
Merged, thanks @laviro!

**Pull request merged**
